### ISSUE TITLE
Can I maintain Elastics?

### ISSUE THREAD

**Issue by devxoul** [tundrabot/Elastics#1]
Hi,
I didn't know that Elastics has been removed from AppStore. (Because I'm still using it properly on my mac)

I love this project and want to maintain. Is it available?

Thanks.

**Comment by geonu** [comment]
:+1:

**Comment by benjamin-chang** [comment]
Add you @devxoul.

**Comment by devxoul** [comment]
@benjamin-chang Thanks. Could you please tell me what can I do and what should not do?

I'd like to rewrite old Elastics code in Swift and make it more scalable to support other AWS services. And AppStore!
